MVCPracticeDataAnnotations/Controllers/PracticeValidationController.cs
using MVCPracticeDataAnnotations.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCPracticeDataAnnotations.Controllers
{
    public class PracticeValidationController : Controller
    {
        // GET: PracticeValidation
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ValidationTest()
        {
            if (ModelState.IsValid)
                return View();

            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult ValidationTest(dataAnnotationTestModel model)
        {
            //dataAnnotationTestModel model = new dataAnnotationTestModel();
            if (ModelState.IsValid)
                return RedirectToAction("Index");
                //return model;

            return View();
            
        }
    }
}

MVCPracticeDataAnnotations/Views/PracticeValidation/Index.cshtml
@model MVCPracticeDataAnnotations.Models.dataAnnotationTestModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div>
        <h4>dataAnnotationTestModel</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.age)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.age)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "ValidationTest", new { /* id = Model.PrimaryKey */ }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

MVCPracticeDataAnnotations/Views/PracticeValidation/ValidationTest.cshtml
@*@model MVCDemo.Models.StudentModel*@
@model MVCPracticeDataAnnotations.Models.dataAnnotationTestModel
@{
    ViewBag.Title = "Add";
    //Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add</h2>
@Html.ActionLink("View List", "ValidationTest", "PracticeValidation")

@using (Html.BeginForm("ValidationTest", "PracticeValidation", FormMethod.Post))
{
    @Html.ValidationSummary()

    <fieldset>
        <legend>Registration Form</legend>
        
        <ol>
            <li>
                @Html.LabelFor(m => m.name)
                @Html.TextBoxFor(m => m.name)
                @Html.ValidationMessageFor(m => m.name)
            </li>
            <li>
                @Html.LabelFor(m => m.age)
                @Html.TextBoxFor(m => m.age)
                @Html.ValidationMessageFor(m => m.age)
            </li>

        </ol>
        <input type="submit" value="Save" />
    </fieldset>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
@{
    Layout = null;
}